### PR TITLE
Remove arch packaging and references

### PR DESCRIPTION
**Pull request by mfontanini**
This is currently outdated and: a) I don't know how to update it b) I don't use arch so I don't know if my attempts to change it work c) I don't have the time to sit down and figure out what needs to be done. I'm all or supporting arch users but I either need someone who can keep this up to date or have clear instructions on how to keep it up to date.

cc @pwnwriter you added this initially but I can't maintain it and I'd rather not mention this as an official way to install the app if it's going to be outdated.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
If you automate the publish this should be easy. Here is how I do for one of my rust project.

* Create an account in https://aur.archlinux.org/ so you can publish.
* Generate PKGBUILD on the fly. Refer to https://github.com/prabirshrestha/rblog/blob/430f70a53df213c7597a55ca1c6865b8a9e78c93/packages/aur/genpkgbuild.sh
* Use the github action to publish aur packages. https://github.com/prabirshrestha/rblog/blob/430f70a53df213c7597a55ca1c6865b8a9e78c93/.github/workflows/ci.yml#L254-L280.
* SSH Keys will be used to publish package so use a new one specific for AUR.

It is ok to have only presenterm-bin.

Would love to see presenterm-bin back.

**Comment by pwnwriter** [comment]
Hello @mfontanini,

I apologize for not checking my emails earlier; I was away. 

You don't need to remove any references. `presenterm-git` still works without any adjustments. The only thing I'd need to modify is the `binary version`, which I'm happy to do unless you prefer to take over the package.

**Comment by mfontanini** [comment]
Hey @pwnwriter, no worries! If you'd like to commit to continuing maintaining this that works for me. I just didn't want to advertise this being available in arch but having an outdated version out there.

**Comment by pwnwriter** [comment]
Done :heavy_check_mark:

**Comment by pwnwriter** [comment]
Btw, @mfontanini,

I suggest adding  some recommendation to consider the use of the `-git` version, as it is compiles directly from the source.

**Pull request merged**
