### PR TITLE
ci: cargo clippy checks all targets for errors

### PR DESCRIPTION
**Pull request by mikavilpas**
This is a continuation of https://github.com/mfontanini/presenterm/pull/231 and should help in keeping all targets linted in the future. That PR only fixed the current situation - this one should make sure things stay clean in the future as well.

### CODE REVIEW

**Comment by mfontanini** [comment]
It's actually complaining about an import with this change, can you address that one? Thanks!

**Comment by mikavilpas** [comment]
Yes, I'm actually just looking into it. I don't seem to be able to reproduce the error locally.

I wonder if CI uses a different version of the toolchain or clippy, or something. I can of course remove the error manually, but it might be annoying to keep CI happy in the future if the errors can't be seen locally.

@mfontanini would you have time to check if `cargo clippy --all-targets -- -D warnings` reports any errors for you?

**Comment by mfontanini** [comment]
I don't see it locally. The problem is the CI is using the latest version of rust (which is a bad idea) so it will complain about things you may not see locally. If you `rustup update` you should see it.

But also this should use a pinned version of rust in the CI, otherwise this can happen. I was going to do that at some point but never did, maybe it's time.

**Comment by mfontanini** [comment]
Closing as these should be fixed.

**Pull request closed without merging**
