### PR TITLE
Add executable blocks

### LINKED ISSUE #4: Allow code execution
It would be great if presenterm had code execution the way [slides](https://github.com/maaslalani/slides#code-execution) does. You'd have a code block, and by pressing `ctrl+e` the code block would be executed.

### PR DESCRIPTION
**Pull request by mfontanini**
This adds code execution for shell blocks (e.g. `bash`, `sh, `shell`, etc) when pressing control+e. For this to work you need to annotate the code block with `+exec` (e.g. `bash +exec`) so that you agree to allow presenterm to run the code. 

I also made this so that you can still change slides as the code is being rendered. Not sure if that's necessary but I think it was simpler to do it this way.

@baduhai would you like to test this and let me know if it works for you? Thanks!

[asciicast](https://asciinema.org/a/1v3IqCEtU9tqDjVj78Pp7SSe2)

Closes #4

### CODE REVIEW

**Comment by mfontanini** [comment]
I'm curious actually how do you expect this to work if the output overflows the screen. I'd like to avoid implementing scrolling if possible, so I guess the alternatives are a) let it overflow and b) truncate and get the last N lines. Thoughts?

**Comment by mfontanini** [comment]
@baduhai I'm merging this because I want to change other stuff and I'll start having conflicts. Let me know if something's off

**Comment by baduhai** [comment]
You merged just as I was testing :)

I'm getting a failed test when compiling, currently:

```
test render::layout::test::layout::case_17_center_margin_and_size_overflows ... ok
test render::properties::test::shrink ... ok
test style::test::color_serde ... ok
test builder::test::preformatted_blocks_account_for_unicode_widths ... ok
test theme::test::validate_themes ... ok

failures:

---- execute::test::shell_code_execution stdout ----
thread 'execute::test::shell_code_execution' panicked at 'execution failed: SpawnProcess(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/execute.rs:166:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    execute::test::shell_code_execution

test result: FAILED. 96 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Gonna try to skip tests to see how it runs.

**Comment by baduhai** [comment]
Interesting, I think I did something wrong on my end before. `cargo test` works just fine when I cloned the entire source, I guess the nix derivation I wrote for this is just missing something.

It works wonderfully, thank you so much for this feature!

**Comment by mfontanini** [comment]
Phew you scared me. Awesome, let me know if you find any issues/need any features!

**Pull request merged**
